name: Test Python

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python_version: 3.11
      - name: install requirements.txt
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest
      - name: Run parsing
        run: python main.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCOUNT_TOKEN: ${{ secrets.ACCOUNT_TOKEN }} 
          
          
